/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs455_martina_final;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.BeforeEach;

class LibraryTest {
    
    User user;

    @BeforeEach
    public void setUp() throws Exception {
        user = new User();
    }
    
    
    
    
    
}
